version: '3.8'

services:
  backend:
    build:
      context: ./studentmanagement
      dockerfile: Dockerfile
    container_name: project-backend
    ports:
      - "8010:8010"
    env_file:
      - ./studentmanagement/.env.production
    restart: always

  frontend:
    build:
      context: ./project-tp01_1_8_51_52_54
      dockerfile: Dockerfile
    container_name: project-frontend
    ports:
      - "3000:80" # 3000 pour accéder en local, Nginx écoute sur 80
    env_file:
      - ./project-tp01_1_8_51_52_54/.env.production
    restart: always
