name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SUBMODULE_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Checkout repo with submodules (using SSH)
      uses: actions/checkout@v3
      with:
        submodules: recursive # Cloner les sous-modules
        ssh-key: ${{ secrets.SUBMODULE_SSH_KEY }}
        fetch-depth: 0  # Prendre tout l'historique (optionnel)
       

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./studentmanagement
        file: ./studentmanagement/Dockerfile
        push: true
        tags: kaloina/project-cicd-backend:latest

    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./project-tp01_1_8_51_52_54
        file: ./project-tp01_1_8_51_52_54/Dockerfile
        push: true
        tags: kaloina/project-cicd-frontend:latest
